### ISSUE TITLE
The -B/-b option (permanently cached branches) doesn't work with -P (prune mode).

### ISSUE THREAD

**Issue by neilstephens** [neilstephens/MiniPlex#1]
The -B/-b option (permanently cached branches) doesn't work with -P (prune mode).

	The reason is that both options manipulate the "EndPointCache" using assumptions that don't hold when both options are enabled:
	
		-B/-b is simply implemented by adding elements to the cache with the "permanent" flag set.
	
		-P assumes that the first (and only) entry in the cache is the active branch and 'prunes' messages from other branches, and relies on the cache entry timing out if it's to ever use another branch.
		Put another way, it doesn't expect any permanent cache entries, so if the first entry is permanent, it's the only branch that will ever be forwarded to/from.
			see "if(Args.Prune && rcv_sender != trunk && cache_EPs.size() && rcv_sender != cache_EPs[0])" in MiniPlex.cpp
		
	Fix Needed:
		Don't store permanent branches in the EndPointCache. Keep a separate collection of permanent branches instead.
		When forwarding packets, use a superset of the cache and permanent branches.

**Comment by neilstephens** [comment]
@jigjnasu, this is the issue I mentioned to you.

**Comment by jigjnasu** [comment]
Thanks @neilstephens !!!

**Comment by neilstephens** [comment]
Needed this fix urgently, so I fixed in 2acff6709b9e3fe0556323d383d84055d6835bfe . Sorry @jigjnasu , I'll tag you on the next 'help wanted' issue. Cheers.
